[BOO-53] Integración notificaciones
BookLinkLab/booklink-front pull request #104
Opened 2023-11-02 21:39 UTC by valentinavalenzi

2023-11-05 12:20 UTC, fabrizioserial commented on src/screens/notifications/index.jsx
> +    const getNotifications = async () => {
Nunca se llama esta funcion

2023-11-05 12:21 UTC, fabrizioserial commented on src/screens/notifications/index.jsx
> +        const response = await getNotifications()
el nombre de la funcion-query es el mismo que el de la funcion de este file, por lo que nunca se llegó a importar y esta referenciandose al mismo file en si

2023-11-05 12:22 UTC, fabrizioserial commented on src/service/apis.js
> +export const getNotifications = async (token) => {
este nombre es el mismo que el de la funcion del otro file, por lo que no se te importa en el otro file

2023-11-05 12:22 UTC, fabrizioserial requested changes
No funca. Deje comments de que puede ser

2023-11-05 12:34 UTC, fabrizioserial commented on src/screens/notifications/index.jsx
> +        const response = await getNotifications()
A la funcionQuery de la linea 20, le falta que le pases el token tambien

2023-11-07 21:44 UTC, CatalinaMendizabal requested changes

2023-11-07 21:44 UTC, CatalinaMendizabal commented on src/screens/notifications/index.jsx
>      const forumName = "Foro de prueba"
borrar los campos de mock

2023-11-07 21:44 UTC, CatalinaMendizabal commented on src/screens/notifications/index.jsx
> +                    forumImg={notification.forumImg}
fijate bien los campos que te trae la requesto, no es `forumImg`, es `img`
```
{
    "notificationId": 10,
    "content": "@pablofernandez creó una nueva publicación en \"1984\"!",
    "authorId": 8,
    "forumId": 3,
    "postId": 5,
    "date": "2023-11-07T21:32:28.250+00:00",
    "seen": false,
    "img": "https://www.storytel.com/images/640x640/0002933941.jpg"
}
```

2023-11-07 21:44 UTC, CatalinaMendizabal commented on src/screens/notifications/index.jsx
> +                    forumImg={notification.forumImg}
- Habria que cambiar el componenten de notificaciones a que reciba: img, content y isSeen
- Del content sacar la información del forumName y posterName
 ```
  const posterName = content.match(/@(\w+)\s/)[1]
   const forumName = content.match(/"([^"]+)"/)[1]
   ```

2023-11-09 11:15 UTC, fabrizioserial approved these changes
LGTM

2023-11-09 11:15 UTC, merged