[BOO-110] Integración alta/baja configuración de notificaciones
BookLinkLab/booklink-front pull request #105
Opened 2023-11-02 21:47 UTC by maxigeist

2023-11-05 12:27 UTC, fabrizioserial commented on src/service/apis.js
> +        return await bookLinkAxios.post(`/notification/${forumId}/toggle`, config(token))
<img width="615" alt="image" src="https://github.com/BookLinkLab/booklink-front/assets/56046397/d2c51941-3bf5-4dee-bd8b-770055cf92a7">
Estas mandando el header como un body.. Alguien no testeo su tarea 👎🏻 

```javascript

return await bookLinkAxios.post(`/notification/${forumId}/toggle`,undefined, config(token))

```

2023-11-05 12:27 UTC, fabrizioserial requested changes
comments

2023-11-07 21:51 UTC, CatalinaMendizabal commented on src/service/apis.js
> +        return await bookLinkAxios.post(`/notification/${forumId}/toggle`, config(token))
capo esta mockeado todavia el tema de las configs por eso falla, no es que no esta testeado ajja

2023-11-09 20:25 UTC, fabrizioserial approved these changes
LGTM

2023-11-09 20:25 UTC, merged