[BOO-59] Configuración integración
BookLinkLab/booklink-front pull request #106
Opened 2023-11-02 21:50 UTC by valentinavalenzi

2023-11-05 12:29 UTC, fabrizioserial requested changes
Mismo error que el otro PR
- No se esta importando la funcion query que llama al GET
- La funcion dentro del componente nunca se ejecuta
- Falta pasarle el token al endpoint

2023-11-07 22:05 UTC, CatalinaMendizabal requested changes

2023-11-07 22:05 UTC, CatalinaMendizabal commented on src/service/apis.js
> +        return await bookLinkAxios.get("/configuration", config(token))
es `/notification/configuration` -> estate atenta siempre a si esta bien o no

2023-11-07 22:05 UTC, CatalinaMendizabal commented on src/screens/settings/index.jsx
> +        const response = getNotificationSettings(token)
falta el await

2023-11-07 22:05 UTC, CatalinaMendizabal commented on src/screens/settings/index.jsx
> +            <Loader open={loading} />
Fijate que estas mapeando mal el forumCards
```
   <ForumNotificationsConfigCard
                            name={card.forumName}
                            img={card.forumImage}
                            switchState={card.notification}
                        />
                   ```
                   Siempre fijate que te devuelve la request porque a veces el mock como no sabemos que devuelve se tratan de imitar los campos pero la mayoria de veces no coinciden

2023-11-07 23:12 UTC, valentinavalenzi commented on src/screens/settings/index.jsx
> +            <Loader open={loading} />
Perfecto, pasa que cuando lo hice no había nada del back entonces no sabía como iba a llegar. Mil disculpass

2023-11-09 00:14 UTC, fabrizioserial approved these changes
LGTM

2023-11-09 00:14 UTC, merged