[BOO-153] Integracion ver foro
BookLinkLab/booklink-front pull request #40
Opened 2023-09-17 19:42 UTC by franciscocavallaro

Todavía falta que desde el back cambien que cuando hago el get del foro en el owner me pasan el username y quedamos en que lo van a cambiar a que sea el id del owner

2023-09-19 14:33 UTC, CatalinaMendizabal requested changes

2023-09-19 14:33 UTC, CatalinaMendizabal commented on src/components/HeaderForum/index.jsx
> +                        tags.map((tag, index) => <Chip key={index} tag={tag} />)
el chip tiene que recibir el name de la tag porque es un objecto
`tags={forum.tags.map((tag) => tag.name)}`

2023-09-19 14:33 UTC, CatalinaMendizabal commented on src/components/HeaderForum/index.jsx
>              {owner ? (
El boton de editar --> tiene que navegar al editForum

2023-09-21 03:58 UTC, CatalinaMendizabal commented
Tiene conflicts :(

2023-09-21 16:39 UTC, fabrizioserial approved these changes
LGTM 👍🏻

2023-09-21 16:40 UTC, merged