[BOO-192] Integración get de todas las etiquetas
BookLinkLab/booklink-front pull request #49
Opened 2023-09-22 13:43 UTC by franciscocavallaro

2023-09-25 21:21 UTC, CatalinaMendizabal requested changes

2023-09-25 21:21 UTC, CatalinaMendizabal commented on src/screens/createForum/index.jsx
> +                console.error("Error fetching tags:", error)
Los errores tienen que mostrarse con el `error toast`

2023-09-25 21:21 UTC, CatalinaMendizabal commented on src/screens/createForum/index.jsx
> +                console.error("Error fetching tags:", error)
Lo mismo tmb en las otras screens

2023-09-25 21:21 UTC, CatalinaMendizabal commented
y tiene conflicts con editForum

2023-09-25 21:22 UTC, franciscocavallaro commented on src/screens/createForum/index.jsx
> +                console.error("Error fetching tags:", error)
dale dale, ahi lo cambio jeje

2023-09-26 19:33 UTC, CatalinaMendizabal requested changes

2023-09-26 19:33 UTC, CatalinaMendizabal commented on src/screens/home/index.jsx
> +        getTags(token)
Falta el import de getTags -> no compila

2023-09-26 19:33 UTC, CatalinaMendizabal commented on src/screens/home/index.jsx
> +                            <AutocompleteMUI
Aca lo mismo, falta el import -> siempre fijate q compile todo bien

2023-09-26 19:36 UTC, CatalinaMendizabal commented on src/screens/home/index.jsx
> +        getTags(token)
Igualmente, sacamos del diseño el filtrar por tags asique borrate todo lo que este linkeado con la call a las tags en el home y mergeate dev antes porque ya lo fletamos a la parte de la UI

2023-09-26 20:16 UTC, CatalinaMendizabal commented on src/screens/createForum/index.jsx
> +    const [tagOptions, setTagOptions] = useState([])
Borrate todo lo de tags que no se use mas, tipo el `handleTagChange` 
`
    const [tags, setTags] = useState([])
    const [selectedTags, setSelectedTags] = useState([])
    `

2023-09-26 20:21 UTC, franciscocavallaro commented on src/screens/createForum/index.jsx
> +    const [tagOptions, setTagOptions] = useState([])
es que eso lo habia hecho lele y por eso no lo queria tocar por las dudas
lo borro todo?

2023-09-26 20:23 UTC, franciscocavallaro commented on src/screens/createForum/index.jsx
> +    const [tagOptions, setTagOptions] = useState([])
mas que nada porque no queria tocar codigo que no sea mio

2023-09-26 20:25 UTC, CatalinaMendizabal approved these changes

2023-09-26 20:25 UTC, merged