Feature/boo 87 navbar
BookLinkLab/booklink-front pull request #6
Opened 2023-08-20 20:38 UTC by franciscocavallaro

Falta poder usar el componente del botón que todavía no esta listo para usar, cuando este listo integro lo que hice con el botón.

2023-08-20 21:14 UTC, fabrizioserial commented on src/assets/icons/notificationBell.js
> +export const notificationBell = ({ height, width, color }) => {
Los componentes siempre arrancan con **Mayuscula**, siguiendo **PascalCase**

2023-08-21 01:51 UTC, fabrizioserial commented on src/screens/createForum/createForum.jsx
> +            <Navbar/>
Por que el componente se repite en varios componentes? 🤔

2023-08-21 02:00 UTC, CatalinaMendizabal commented on src/App.js
> +                <Route path='/createForum' element={<CreateForum/>}/>
Agregar la Navbar antes de las routes. Asi no se tiene que llamar en cada uno de los files que se va a utlizar.

2023-08-21 02:03 UTC, CatalinaMendizabal commented on src/components/navbar/index.jsx
> +                <div className="logo">
Agregar on click en el logo que haga el navigate al `/home`

2023-08-21 02:06 UTC, CatalinaMendizabal commented on src/screens/createForum/createForum.jsx
> +            <Navbar/>
Sacar todas las navbars de las screens, asi se usa unicamente en App.js

2023-08-21 02:08 UTC, CatalinaMendizabal commented
Conflicts :(

2023-08-21 20:55 UTC, CatalinaMendizabal approved these changes

2023-08-21 21:01 UTC, CatalinaMendizabal requested changes

2023-08-21 21:01 UTC, CatalinaMendizabal commented on src/components/navbar/index.jsx
> +            <div className="left-content">
agregar el onClick aca en vez de en el logo unicamente, asi si clickeo en el text tambien me hace el navigate

2023-08-21 21:01 UTC, CatalinaMendizabal commented on src/components/navbar/styles.css
> +    align-items: center;
agregar curso: pointer asi cuando pongo el mouse sobre el texto me dice que es clickeable

2023-08-21 21:29 UTC, fabrizioserial commented
🚨 **Nombre del PR** 🚨

2023-08-21 22:00 UTC, CatalinaMendizabal approved these changes

2023-08-21 22:00 UTC, merged