[BOO-165] Ver post
BookLinkLab/booklink-front pull request #72
Opened 2023-10-05 17:14 UTC by valentinavalenzi

2023-10-08 21:17 UTC, CatalinaMendizabal requested changes

2023-10-08 21:17 UTC, CatalinaMendizabal commented on src/components/Comment/index.jsx
>      const [openModal, setOpenModal] = useState(false)
Falta el import del useState

2023-10-08 21:17 UTC, CatalinaMendizabal commented on src/screens/comments/index.jsx
> +                    style={{ width: 40, height: 40 }}
Todos los inline styles pasalos al styles.css asi sigue la misma estrucutra que venimos usanod

2023-10-08 21:17 UTC, CatalinaMendizabal commented on src/screens/comments/index.jsx
> +            <AddPost buttonText={"Comentar"} textFieldPlaceholder={"Comparte tus ideas..."} />
Le falta un margin bottom asi no queda pegado completamente con el fondo de la pagina

2023-10-08 21:17 UTC, CatalinaMendizabal commented on src/screens/comments/styles.css
> +    margin-bottom: 117px;
cambiale el `margin-bottom: 80px;`

2023-10-09 22:18 UTC, CatalinaMendizabal commented
conflicts :c

2023-10-10 11:52 UTC, fabrizioserial approved these changes

2023-10-10 11:53 UTC, merged