[BOO-101] Integración editar posteo
BookLinkLab/booklink-front pull request #74
Opened 2023-10-10 00:31 UTC by lelemustdie

2023-10-18 21:18 UTC, CatalinaMendizabal requested changes

2023-10-18 21:18 UTC, CatalinaMendizabal commented on src/components/Comment/index.jsx
> +import withToast from "../../hoc/withToast"
esta importado dos veces, no compila

2023-10-18 21:18 UTC, CatalinaMendizabal commented on src/service/apis.js
>  export const updateComment = async (token, id, content) => {
no compila, falta cerrarlo

2023-10-18 21:18 UTC, CatalinaMendizabal commented
conflicts :/

2023-10-19 02:22 UTC, fabrizioserial approved these changes
LITM (Look impecable to merge) 👍🏻

2023-10-19 02:23 UTC, merged