[BOO-100] Integración
BookLinkLab/booklink-front pull request #75
Opened 2023-10-11 19:06 UTC by valentinavalenzi

Falta que Maxi suba algunas cosas que hicimos juntos para mergear bien eso

2023-10-17 00:36 UTC, fabrizioserial commented on src/screens/comments/index.jsx
>                  {comments.map((item) => (
Agreguemos `postInfo.comments`

2023-10-17 00:37 UTC, fabrizioserial commented on src/screens/comments/index.jsx
>                  {comments.map((item) => (
porque rompe je

2023-10-17 00:44 UTC, fabrizioserial commented on src/components/Comment/index.jsx
> +    const commentId = useParams()
`const {commentId} = useParams()`

2023-10-18 21:32 UTC, CatalinaMendizabal requested changes

2023-10-18 21:32 UTC, CatalinaMendizabal commented on src/components/Comment/index.jsx
>      const { token } = useCurrentUser()
falta el import, esta rompiendo

2023-10-18 21:32 UTC, CatalinaMendizabal commented on src/screens/comments/index.jsx
> +            const response = await deletePost(token, commentId)
si es deletePost deberias pasarle el postId no commentId

2023-10-19 18:05 UTC, fabrizioserial commented
Cerramos este PR porque la logica esta duplicada en otro PR y ya otro dev lo integró 👍🏻

2023-10-19 18:05 UTC, closed without merging