[BOO-47] Lógica de foro
BookLinkLab/booklink-front pull request #80
Opened 2023-10-18 12:26 UTC by valentinavalenzi

2023-10-18 21:05 UTC, CatalinaMendizabal requested changes

2023-10-18 21:05 UTC, CatalinaMendizabal commented on src/screens/forum/index.jsx
> +                {id === forum.ownerId &&
el chequeo que se tiene que hacer es `forum.searcherIsMember` y deberia hacerse **antes** del componente del `AddPost`

2023-10-18 21:05 UTC, CatalinaMendizabal commented on src/screens/forum/index.jsx
> +                            commentText={post.content}
falta un index o id porque es un map y se renderiza multiples veces

2023-10-19 19:17 UTC, fabrizioserial commented on src/screens/comments/index.jsx
> +            {!!openModal && (
Borrar esta logica de Borrar post. No es accesible (fijate que el setOpenModal esta dentro del openModal, por lo que no se puede abrir)

2023-10-19 19:19 UTC, fabrizioserial commented on src/screens/comments/index.jsx
> +    const { commentId, postId } = useParams()
commentId no existe (`/forum/:forumId/post/:postId`). Igual leete el comment de abajo, que ya no vamos a necesitar esta variable

2023-10-22 13:25 UTC, CatalinaMendizabal submitted a review, later dismissed

2023-10-24 20:31 UTC, fabrizioserial commented on src/screens/forum/index.jsx
> +                            onSubmit={(comment) => handleAddPost(comment)}
Cuando agrego un post, no se actualiza la pagina.  Agregate denuevo lo que estaba antes
`                    onSubmit={(comment) => handleAddPost(comment).then(getPostsData)}`

2023-10-24 20:57 UTC, valentinavalenzi commented on src/screens/forum/index.jsx
> +                            onSubmit={(comment) => handleAddPost(comment)}
Perfecto!!

2023-10-24 21:05 UTC, fabrizioserial commented
No aparece las opciones de editar ni eliminar en mi propio post
<img width="758" alt="image" src="https://github.com/BookLinkLab/booklink-front/assets/56046397/42abb9e4-9c97-48ae-9a29-162e417188a7">

En los comentarios si
<img width="443" alt="image" src="https://github.com/BookLinkLab/booklink-front/assets/56046397/0c13d3e5-4778-43df-b361-cc1d3028d1c6">

2023-10-25 01:01 UTC, fabrizioserial approved these changes

2023-10-25 01:01 UTC, merged