[BOO-106] Integración editar comentario
BookLinkLab/booklink-front pull request #86
Opened 2023-10-20 15:54 UTC by lelemustdie

2023-10-25 22:20 UTC, CatalinaMendizabal requested changes

2023-10-25 22:20 UTC, CatalinaMendizabal commented on src/service/apis.js
> +        return await bookLinkAxios.patch(`/comment/${id}`, { content }, config(token))
falta codigo aca

2023-10-26 01:01 UTC, CatalinaMendizabal commented
y conflicts

2023-10-26 02:43 UTC, fabrizioserial approved these changes
LGTM

2023-10-26 02:43 UTC, merged