[BOO-27] Pantalla Login
BookLinkLab/booklink-front pull request #9
Opened 2023-08-21 14:40 UTC by maxigeist

Login screen implemented

2023-08-21 21:05 UTC, CatalinaMendizabal commented on src/App.js
> +                <Route path="/login" element={<Login />}></Route>
En vez de 
`<Route path="/login" element={<Login />}></Route>` cerrar la empty tag
`<Route path="/login" element={<Login />} />`

2023-08-21 21:10 UTC, maxigeist commented on src/App.js
> +                <Route path="/login" element={<Login />}></Route>
Dale genial, ahora lo cambio

2023-08-21 21:36 UTC, CatalinaMendizabal requested changes

2023-08-21 21:36 UTC, CatalinaMendizabal commented on src/screens/login/index.jsx
> +                    Email: "",
initial values en lowercase

2023-08-21 21:36 UTC, CatalinaMendizabal commented on src/screens/login/index.jsx
> +                    <div className="login-div-1">
- este div lo podes sacar y agregarle el className en <Form>
- el nombre del div puede ser login-form-container o algo así mas que login-div-1
- Podes agregar el justify-content: center y te ahorras de del div del logo y el className `login-logo-div` que lo unico que hace es centrarlo

2023-08-21 21:36 UTC, CatalinaMendizabal commented on src/components/Logo/index.jsx
> +            <div>
este div se puede sacar

2023-08-21 21:36 UTC, CatalinaMendizabal commented on src/components/Logo/index.jsx
> +            <div>
- este div tambien se puede sacar -> con total si el name existe se renderiza el div y sino nada
- Si no se cumple la condicion y devuelve null se puede hacer tambien asi
`  {name && 
                   <div className="logo-name-inline-container">
                        <Header className={sizes[size] + " bold"}>Book</Header>
                        <Header className={sizes[size]}>Link</Header>
                    </div>
                }
                ` y te ahorras el : null

2023-08-21 21:36 UTC, CatalinaMendizabal commented on src/components/Logo/index.jsx
> +                    <div className="logo-name-inline-container">
Aca lo que se puede hacer sino, para no tener que agregar el "bold" en el class name es usar el tag <b> 
`{name && <Header className={sizes[size]}><b>Book</b>Link</Header>}` 

(lo podes dejar como esta, pero para que tengas el dato)

2023-08-21 21:37 UTC, CatalinaMendizabal commented on src/screens/login/index.jsx
> +                                <Button size="large" disabled={loading} variant="ghost">
agregar el onClick que haga el navigate a `/register`

2023-08-22 15:47 UTC, CatalinaMendizabal approved these changes

2023-08-22 15:47 UTC, merged